//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talpa_10_WebApp.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared_nl_NL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared_nl_NL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talpa_10_WebApp.Resources.Translations.Shared.nl-NL", typeof(Shared_nl_NL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegang geweigerd.
        /// </summary>
        internal static string Access_Denied {
            get {
                return ResourceManager.GetString("Access Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Er is een fout opgetreden bij het verwerken van uw verzoek.
        /// </summary>
        internal static string An_error_occurred_while_processing_your_request {
            get {
                return ResourceManager.GetString("An error occurred while processing your request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit wilt verwijderen?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug naar overzicht.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmaken.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe Aaanmaken.
        /// </summary>
        internal static string Create_New {
            get {
                return ResourceManager.GetString("Create New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datums.
        /// </summary>
        internal static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werknemer.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout tijdens het aanmaken.
        /// </summary>
        internal static string Error_while_creating {
            get {
                return ResourceManager.GetString("Error while creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout tijdens het verwijderen.
        /// </summary>
        internal static string Error_while_deleting {
            get {
                return ResourceManager.GetString("Error while deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout tijdens het wijzigen.
        /// </summary>
        internal static string Error_while_updating {
            get {
                return ResourceManager.GetString("Error while updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout tijdens het koppelen van de gebruikers.
        /// </summary>
        internal static string Error_white_attaching_users {
            get {
                return ResourceManager.GetString("Error white attaching users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kikker.
        /// </summary>
        internal static string Frog {
            get {
                return ResourceManager.GetString("Frog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Pagina.
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item succesvol aangemaakt.
        /// </summary>
        internal static string Item_successfully_created {
            get {
                return ResourceManager.GetString("Item successfully created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successvol verwijderd.
        /// </summary>
        internal static string Item_successfully_deleted {
            get {
                return ResourceManager.GetString("Item successfully deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item succesvol gewijzigd.
        /// </summary>
        internal static string Item_successfully_updated {
            get {
                return ResourceManager.GetString("Item successfully updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitloggen.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheer uitjes.
        /// </summary>
        internal static string ManageOutings {
            get {
                return ResourceManager.GetString("ManageOutings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat geen entiteit met dit id.
        /// </summary>
        internal static string No_entity_found_with_this_id {
            get {
                return ResourceManager.GetString("No entity found with this id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen gebruikers geselecteerd.
        /// </summary>
        internal static string No_users_selected {
            get {
                return ResourceManager.GetString("No users selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitje.
        /// </summary>
        internal static string Outing {
            get {
                return ResourceManager.GetString("Outing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit uitje bestaat niet.
        /// </summary>
        internal static string Outing_does_not_exist {
            get {
                return ResourceManager.GetString("Outing does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te plannen uitjes.
        /// </summary>
        internal static string OutingsToPlan {
            get {
                return ResourceManager.GetString("OutingsToPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beperkingen.
        /// </summary>
        internal static string Restrictions {
            get {
                return ResourceManager.GetString("Restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorebord.
        /// </summary>
        internal static string Scoreboard {
            get {
                return ResourceManager.GetString("Scoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer dagen.
        /// </summary>
        internal static string SelectDays {
            get {
                return ResourceManager.GetString("SelectDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestie.
        /// </summary>
        internal static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggesties.
        /// </summary>
        internal static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikers.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom bij TALPA!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent niet aan een team toegewezen.
        /// </summary>
        internal static string You_are_not_assigned_to_a_team {
            get {
                return ResourceManager.GetString("You are not assigned to a team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///U heeft geen toegang tot deze bron.
        /// </summary>
        internal static string You_do_not_have_access_to_this_resource {
            get {
                return ResourceManager.GetString("You do not have access to this resource", resourceCulture);
            }
        }
    }
}
