# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: download images
      run: |
        mkdir images && 
        curl -o images/sample.png https://jensramakers.nl/assets/img/portfolio/cube.png

    - name: verify images exists
      run: |
        ls -la images

    - name: Create Database
      run: |
        sudo systemctl start mysql
        mysql --user="root" --password="" -e "CREATE DATABASE \`Talpa\` character set UTF8mb4 collate utf8mb4_bin;"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      working-directory: source/Talpa
      run: dotnet restore
      
    - name: Build
      working-directory: source/Talpa
      run: dotnet build --no-restore
      
    - name: Test
      working-directory: source/Talpa
      run: dotnet test --no-build --verbosity normal
